line-length = 120
exclude = [
    ".git",
    ".venv",
    ".vscode",
    "build",
]
target-version = "py310"

[lint]
select = [
    "A",
    "B",
    "C",
    "E",
    "F",
    "FURB",
    "I",
    "RUF",
    "TC",
    "UP",
    "W",
]