name: CI

on:
  pull_request:
    branches:
      - develop

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.9"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies (3lc from PyPI)
        run: uv sync --no-sources --python 3.9

      - name: Run ruff formatter
        run: uv run --no-sync --python 3.9 ruff format --check .

      - name: Run ruff linter
        run: uv run --no-sync --python 3.9 ruff check .

      - name: Run tests
        run: |
          export $(echo ${{ secrets.VARIABLE_NAME }})=${{ secrets.VARIABLE_VALUE }}
          export $(echo ${{ secrets.RUNTIME_NAME }})=${{ secrets.RUNTIME_VALUE }}
          export TLC_API_KEY=${{ secrets.TLC_API_KEY }}
          uv run --no-sync --python 3.9 pytest tests/test_tlc_ultralytics.py

      - name: Minimize uv cache
        run: uv cache prune --ci